version: '2.3'

services:
  dbus-services:
    stop_grace_period: 3s
    environment:
      DEVELOPMENT: 1
    volumes:
      - './test/lib/dbus/systemd.ts:/usr/src/app/systemd.ts'
      - './test/lib/dbus/login.ts:/usr/src/app/login.ts'

  sut:
    stop_grace_period: 3s
    command: sleep infinity
    volumes:
      - './.mochapodrc.yml:/usr/src/app/.mochapodrc.yml'
      - './src:/usr/src/app/src'
      - './test:/usr/src/app/test'
