name: balenaCloud 

on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master

jobs:
  deploy-release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        arch: [aarch64, amd64, armv7hf, i386, rpi]
        environment: [ { tld: balena-cloud.com, token_prop_name: BALENA_TOKEN }, { tld: balena-staging.com, token_prop_name: BALENA_STAGING_TOKEN } ]
    steps:
      - uses: actions/checkout@v2
      - uses: balena-io/balena-ci@master
        name: 'Deploy to ${{ matrix.environment.tld }}'
        with:
          balena_token: ${{ secrets[matrix.environment.token_prop_name] }}
          fleet: 'balena_os/${{ matrix.arch }}-supervisor'
          versionbot: true
          environment: ${{ matrix.environment.tld }}
